// Code generated by "stringer -type=ConditionKind"; DO NOT EDIT.

package gene

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoCondition-0]
	_ = x[TickIsEven-1]
	_ = x[ConditionCount-2]
}

const _ConditionKind_name = "NoConditionTickIsEvenConditionCount"

var _ConditionKind_index = [...]uint8{0, 11, 21, 35}

func (i ConditionKind) String() string {
	if i < 0 || i >= ConditionKind(len(_ConditionKind_index)-1) {
		return "ConditionKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConditionKind_name[_ConditionKind_index[i]:_ConditionKind_index[i+1]]
}
