// Code generated by "stringer -type=GeneKind"; DO NOT EDIT.

package gene

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[North-1]
	_ = x[South-2]
	_ = x[East-3]
	_ = x[West-4]
	_ = x[GeneCount-5]
}

const _GeneKind_name = "IdleNorthSouthEastWestGeneCount"

var _GeneKind_index = [...]uint8{0, 4, 9, 14, 18, 22, 31}

func (i GeneKind) String() string {
	if i < 0 || i >= GeneKind(len(_GeneKind_index)-1) {
		return "GeneKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GeneKind_name[_GeneKind_index[i]:_GeneKind_index[i+1]]
}
